#! /bin/sh

pipewire &
pipewire-pulse &
picom --experimental-backends > /dev/null &
pgrep -x sxhkd > /dev/null || sxhkd &
polybar>/dev/null &

bspc monitor -d 1 2 3 4 5 6 7 8 9

# follow mouse for focus
bspc config focus_follows_pointer true

bspc config top_padding		35
bspc config bottom_padding	-5
bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color \#CFCFCF
bspc config normal_border_color	\#A9A9A9

bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
